version: "3.9"
services:
  api:
    build:
      context: ./services/api
    command: pnpm run dev
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./services/api:/app
    restart: unless-stopped
