version: "3.9"
services:
  api:
    build: ./services/api
    container_name: compta_auto_api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./demo:/app/demo
      - ./infra:/app/infra
